DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Music;
DROP TABLE IF EXISTS Recycledj;
DROP TABLE IF EXISTS Dvalentino;
DROP TABLE IF EXISTS Rusowsky;
DROP TABLE IF EXISTS Lhaine;
DROP TABLE IF EXISTS Judeline;
DROP TABLE IF EXISTS Hoke;
DROP TABLE IF EXISTS Juicybae;
DROP TABLE IF EXISTS Teolucadamo;
DROP TABLE IF EXISTS Delaossa;
DROP TABLE IF EXISTS Boncalso;
DROP TABLE IF EXISTS Stickyma;
DROP TABLE IF EXISTS Diego900;

CREATE TABLE Users (
  userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(512) NOT NULL,
  firstName VARCHAR(256) NOT NULL,
  lastName VARCHAR(256) NOT NULL,
  username VARCHAR(256) NOT NULL
);

CREATE TABLE Music (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL
);

CREATE TABLE Recycledj (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Dvalentino (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Rusowsky (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Lhaine (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Judeline (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Hoke (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Juicybae (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Teolucadamo (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Delaossa (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Boncalso (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Stickyma (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);

CREATE TABLE Diego900 (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL,
  spotify_id VARCHAR(255) NOT NULL
);