DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Music;

CREATE TABLE Users (
  userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(256) UNIQUE NOT NULL,
  password VARCHAR(512) NOT NULL,
  firstName VARCHAR(256) NOT NULL,
  lastName VARCHAR(256) NOT NULL,
  username VARCHAR(256) NOT NULL
);

CREATE TABLE Music (
  musicId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  artista VARCHAR(100) NOT NULL,
  fecha_publicacion DATE NOT NULL
);